server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://10.10.0.12:3380/hs_gas?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gas
    password: gas

  #静态页面路径设置
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  #热部署
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
mybatis-plus:
  mapper-locations: classpath*:/com/sbveu/demo/mapper/*Mapper.xml
  global-config:
    banner: false
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
